### PR TITLE
docs(translation): 🚧 italian translation

### PR DESCRIPTION
**Pull request by lucafano04**
Started italian translation

### CODE REVIEW

**Comment by AloisSeckar** [comment]
This is a great job and I will be happy to incorporate Italian into the system ASAP.

I recently added [nuxt-content module](https://github.com/AloisSeckar/WBSC-Scoring/commit/08dfaffa22e40423c773949d789bcec37902907f) which makes things a little more complicated for translations, as `/help`, `/project` and `/report` now become stand-alone pages that has to be translated separately. But it is cleaner to use Markdown syntax than maintaining JSON file with html syntax.

I am thinking of an optimization right now, as I think there can be only one "change log" containing version history written in English, which is not necessary to translate into every language. Also I suspect "Report bug" page can at least be simplified for languages other than English.

**Comment by lucafano04** [comment]
Note i did not find the string for:
Unerned Run - Punto non guadagnato
Earned Run - Punto guadagnato

**Comment by lucafano04** [comment]
remarked as draft since i foud the .md files 🙃, this will take longer than expected

**Comment by AloisSeckar** [comment]
> remarked as draft since i foud the .md files 🙃, this will take longer than expected

I really think you shouldn't translate whole project history at least. This is more technical thing. I will create `changelog.md` file in project root and just link it from `/project` page later today.

**Comment by AloisSeckar** [comment]
> Note i did not find the string for: Unerned Run - Punto non guadagnato Earned Run - Punto guadagnato

This is because those currently appear only as abbreviations in UI:

image

Do you think it will be worth to add the full description? Maybe we should, so the rookie scorers won't get confused 🤔

**Comment by lucafano04** [comment]
> Do you think it will be worth to add the full description? Maybe we should, so the rookie scorers won't get confused 🤔

Maybe a description would be helpfull but not on that GUI it will be too overcrowded I think

**Comment by AloisSeckar** [comment]
Project history moved to CHANGELOG.md in a7e2bdd71b9f73542f98eaa949b33593d3d9ddb4 => less things to translate in `project.md`

**Comment by AloisSeckar** [comment]
In fede9a87242af27be06380a0bbb0f088d48314c3 I had to make some changes in `help.md` and `report.md` because overflowing images. So please make sure you sync yours with the current version to aviod glitches. No changes in texts, just the contents of image components.

**Comment by lucafano04** [comment]
> In [fede9a8](https://github.com/AloisSeckar/WBSC-Scoring/commit/fede9a87242af27be06380a0bbb0f088d48314c3) I had to make some changes in `help.md` and `report.md` because overflowing images. So please make sure you sync yours with the current version to aviod glitches. No changes in texts, just the contents of image components.

inside commit [`5e6062a`](https://github.com/AloisSeckar/WBSC-Scoring/pull/221/commits/5e6062a7c74448957c1dc70f1bb85a5fa03ccab3) the immages are fixed for `help.md`

**Comment by lucafano04** [comment]
All pages (that I found) has been translated, in the evening I will do a final check and than it can be merged

**Comment by AloisSeckar** [comment]
in 7fa7bcaad4401c511e6397f62072ea43fab94dc3 I added two new messages to `.json` files

after adding those two, we can merge, and I'll publish new version `1.1`

**Comment by lucafano04** [comment]
Done and ready

**Review by AloisSeckar — APPROVED** [review]

**Comment by AloisSeckar** [comment]
Published. Unfortunatelly we hit the roadblock with the release - #227 😢  I am up after it

**Comment by AloisSeckar** [comment]
Should be alright now with https://github.com/AloisSeckar/WBSC-Scoring/releases/tag/v1.1.1

**Pull request merged**
